### ISSUE TITLE
Live editor

### ISSUE THREAD

**Issue by wamoyo** [knsv/mermaid#115]
Mermaid is awesome! This is exactly what I need, love the syntax.

So, this might not be useful for this release, but it would be interesting to have a live editor. I've been editing markdown files and using `mermaid file.md` to make PNGs, also a genius feature, @kentcdodds!

**Comment by knsv** [comment]
Thanks!

There are some editors around. For instance this one that @naseer is working on integrating into the project.
https://github.com/naseer/mermaid-webapp

Also there is a markdown editor in haropad as well as lighttable (with a plugin). Not sure what version of mermaid they are at though. Planning on adding a page in the documentation describing downstream tools with mermaid support.

Also there are work done so that you can include mermaid diagrams in:
* docpad sites - http://nauvalatmaja.com/2015/01/13/rendering-mermaid-in-docpad/
* Jekyll - https://github.com/jasonbellamy/jekyll-mermaid
* gitbook also as a plugin - https://github.com/JozoVilcek/gitbook-plugin-mermaid

**Comment by wamoyo** [comment]
Haa, sweet! This looks awesome.
