### ISSUE TITLE
Support PlantUML syntax

### ISSUE THREAD

**Issue by gembin** [knsv/mermaid#149]
Any plan to support PlantUML syntax ?
http://plantuml.sourceforge.net

**Comment by knsv** [comment]
I am assuming you are thinking about diagram types supported by plantUml other then sequence diagrams.

I think it is in the spirit of mermaid and would fit fine into the roadmap. There are no active plans right now though. Perhaps we should add issues for the the different diagram types and make a poll? 

The possibility of piggyback on the syntax is a plus.

**Comment by gembin** [comment]
Yes,  other diagram types could be also very useful. The mermaid sequence diagram syntax is quite similar to the PlantUml sequence diagram.  It would be great if mermaid can support more types. :-)

Other useful types:
```
Sequence diagram,  Usecase diagram, Class diagram, Activity diagram, Component diagram, 
State diagram, Object diagram.
```

**Comment by knsv** [comment]
Take a look at issue #177. Meanwhile I will close this issue. Let me know if you feel differently

**Comment by WolfgangFahl** [comment]
I think this issue should be reopened and the plantuml syntax should be optionally support or a convert be made available.

**Comment by Edwardlin-zlt** [comment]
> I think this issue should be reopened and the plantuml syntax should be optionally supported or a converter is made available. Especially the theming options of plantuml need to be "translated".

Yes, since a lot of projects treat `plantuml` as code document, and those older project won't change it from plantuml code to mermaid. But for self user like me who think mermaid is much convenient because I can write it using my note software and render diagrams in real time. But once I finish with mermaid code, I want to put it back to the code base as document, I found that there's no converter, thus I was forced back to plantuml.

So, I how mermaid could have a converter to convert mermaid code to plantuml code, or support plantuml syntax directly.

**Comment by naturallymitchell** [comment]
> So, I hope mermaid could have a converter to convert mermaid code to plantuml code, or support plantuml syntax directly.

I agree, so also request reopening this issue.
