### ISSUE TITLE
Windows - cli - could not find phantomjs at the specified path

### ISSUE THREAD

**Issue by raghur** [knsv/mermaid#236]
Phantomjs is on the path. Both mermaid and phantomjs are installed globally.

```
C:\Users\xxxxxxxxxxxxxxxxxx>phantomjs
phantomjs> ^CTerminate batch job (Y/N)?
C:\Users\raghuramanr.STC>mermaid

You had errors in your syntax. Use --help for further information.
You must specify at least one source file.
Could not find phantomjs at the specified path.

C:\Users\xxxxxxxxxxxxxxxxxx>where phantomjs
C:\Program Files\nodejs\phantomjs
C:\Program Files\nodejs\phantomjs.cmd

C:\Users\xxxxxxxxxxxxxxxxxx>phantomjs -v
1.9.8

C:\Users\xxxxxxxxxxxxxxxxxx>node -v
v4.2.1
```

**Comment by JasperTack** [comment]
I have encountered something similar when calling mermaid manually with nodejs. It turns out there is a bug in the cli.js file where phantomjs is being called. The error is caused by spaces in the filepath of the phantomjs executable on line 185 in cli.js:
https://github.com/knsv/mermaid/blob/master/lib/cli.js#L185

When putting the path of phantomjs between quotes like this
```javascript
exec('"' + phantomPath + '" --version', function(err, stdout, stderr) {...}))
```
phantomjs should be found.

**Comment by knsv** [comment]
Thanks @JasperTack. This should be an easy fix.

**Comment by raghur** [comment]
@JasperTack Thanks! I just sent in a pr as I have to work with windows :(

-R
