### ISSUE TITLE
The need for mermaid.css should be mentioned explicitly in the intro docs...

### ISSUE THREAD

**Issue by manor** [knsv/mermaid#273]
The section introducing [simple usage on a web page](http://knsv.github.io/mermaid/#simple-usage-on-a-web-page) doesn't mention the need for `mermaid.css`, which means that if one is following the docs literally, the resulting network renders incorrectly... Maybe it is obvious that CSS will be necessary, but I, for one, had to generate this:

| without CSS | with CSS |
| --- | --- |
| ![without_css](https://cloud.githubusercontent.com/assets/596326/12023751/9d071178-ad6a-11e5-884a-c131bd65cbd7.png) | ![with_css](https://cloud.githubusercontent.com/assets/596326/12023761/bb123c2e-ad6a-11e5-9b25-cee1715def43.png) |

before realizing that there was something missing :-)

It's a shame that there is no way to package things such that the CSS file is rendered unnecessary by default, but I don't know if there is a way to do this without clobbering user-provided customization. At any rate, it is a little jarring to have the nodes appear black and the edges disappear entirely in the absence of `mermaid.css`.

``` html
<script src="https://cdn.rawgit.com/knsv/mermaid/0.5.6/dist/mermaid.min.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/knsv/mermaid/0.5.6/dist/mermaid.css">
<script>mermaid.initialize({startOnLoad:true});</script>
<div class="mermaid">
graph TD;
    A-->B(B)
    A-->C>C]
    B-->D((D))
    C-->D
classDef eco fill:green;
class A,B,C,D eco
</div>
```

**Comment by mniinio** [comment]
I also spent some time before I found 4 things related to the styling because they were not documented at all or clearly:

- what was the latest version (had to understand to click the link "example mermaid x.x.x." in the docs, where the link was actually saying an old version
- mermaid.css (finally found it in the list of files from the cdn)
- how to solve issue with configuration where all html styles were copied which broke all other styles in my page https://github.com/knsv/mermaid/issues/157  cloneCssStyles: false
- and here in this issue finally found the proper example of how to use my own styles with classDef - but none of the examples (even in this issue) are working for me (version 0.5.6) either with css-classes or classes. Using "style" works just like documented

**Comment by knsv** [comment]
Thanks, good feedback! Hard to know what is clear/unclear in the docs

**Comment by Jmuccigr** [comment]
+1.

But what's the version of other css to use from my local install? There are three of mermaid.forest, for example:

./mermaid/dist/mermaid.forest.css
./mermaid/dist/www/stylesheets/mermaid.forest.css
./mermaid/docs/site/stylesheets/mermaid.forest.css

**Comment by nrfm** [comment]
+1

**Comment by objectivephoenix** [comment]
The link committed in this merge is now invalid. I can't find the link to download `mermaid.css` anywhere.
