### ISSUE TITLE
Support for hyperlink and tooltip

### ISSUE THREAD

**Issue by yangpu** [knsv/mermaid#34]
Can we use markdown syntax for define hyperlink and tooltip for interactive?

**Comment by DCushmanDev** [comment]
This would be an excellent feature. (Is there any way to add an <a href=""> tag now? Everything I have tried seems to blow up the chart.)

**Comment by lgersman** [comment]
:+1:

**Comment by knsv** [comment]
This could be done! This is will not work outside the browser so the case with this syntax need to be covered for that case also. I would suggest syntax as per below:
```
click a1,b1 callBackFun
click a2,b2 link

tooltip a1,b1 Tooltip text 1
tooltip a2,b2 Tooltip text 2
```

where a1,2,b1 and b2 are nodes.

**Comment by knsv** [comment]
This in progress now. Will use the following syntax:

click a1,b1 callBackFun
click a2,b2 callBackFun "tooltip text"
click a3,b3 "link"
click a4,b4 "link" "tooltip text"

**Comment by lgersman** [comment]
Good proposal - the syntax looks promising !

**Comment by knsv** [comment]
A fix is committed, but not yet released. Usage is described in the docs:
http://knsv.github.io/mermaid/#interaction

**Comment by knsv** [comment]
Fix for this issue was released in mermaid 0.5.2. Will close this now, let me know if you issues still remain.

**Comment by piranna** [comment]
I think mouse pointer should change to a hand when it's over a clickable element, if not it's not possible to know it. Also would be good to change them on over to show them too. Both things are just a matter of a bit CSS...

Another thing that I've seen is that the "open in a new window" behaviour should be configurable, because I want to use as an image map to other elements on the same page. In that way, if links could be done with regular HTML `a` tags instead of the need of Javascript that would be a plus, because it would be used on PDFs too.

**Comment by majinliang123** [comment]
How could i just show tooltip text, not a link node
