### ISSUE TITLE
Text in notes displays incorrectly when combining Mermaid and Remark (with example)

### ISSUE THREAD

**Issue by hartzell** [knsv/mermaid#360]
When I combine [remark](https://github.com/gnab/remark) and [mermaid](https://github.com/knsv/mermaid) text in notes in sequence diagrams does not seem to be taken into account when the diagram is drawn if the diagram is not on the slide currently being displayed.

I see the problem on a Mac running 10.10.5 in Chrome and in Safari.

I've created a repository, https://github.com/hartzell/remark-mermaid, that contains a demonstration of the problem.

The file _bad.jpg_ in the repository shows what it looks like when it's wrong.

If you redraw the slide, then _that slide_ is correct, but other slides are still screwy.

The file _good.jpg_ in the repository shows what it looks like when it's right.

If you clone the repository and open _talk.html_ you should see an example of the problem.

**Comment by RReverser** [comment]
Same issue when using with Reveal.js - renders correctly on active & nearby slides, but not on the lazy ones.

**Comment by utdrmac** [comment]
+1'ing this as well. Have been using RemarkJS for some time. Recently discovered Mermaid. Trying to integrate the two. As above, slides that are hidden get incorrect SVG. I suspect this has something to do with mermaid needing to know the size of the parent DIV. Since the parent DIV on a hidden slide is sorta 'undefined', mermaid does the best it can.

Is there any way in mermaid to explicitly set the size? Slides don't change size during presentation.

**Comment by RReverser** [comment]
I actually fixed my problem with Reveal.js by applying Mermaid only to the current slide on `slidechange` event.

**Comment by utdrmac** [comment]
@RReverser Could you share that code snippet?

**Comment by RReverser** [comment]
@utdrmac 

Sure, it's here: https://github.com/RReverser/odessajs-2016/blob/gh-pages/index.html#L101-L104

**Comment by utdrmac** [comment]
Hrm. I implemented this similarly for RemarkJS

```javascript
slideshow.on('afterShowSlide', function(s) {
	mermaid.init(undefined, document.getElementById('mermaid0'));
}
```

But it still doesn't render properly. Additionally, RemarkJS doesn't provide each slide as a DOM object. It only supplies the "inner html" of each slide on the event change. I saw your CSS that sets the `svg` block to a specific size. I'll try that next to see if I can force Mermaid to calculate correctly.

**Comment by utdrmac** [comment]
I take that back. Looks like I got it.

```javascript
mermaid.initialize({
  startOnLoad: false,
  cloneCssStyles: false
});

slideshow.on('afterShowSlide', function(s) {
	if (s.properties.mermaid !== undefined)
	{
		var divId = s.properties.mermaid;
		mermaid.init(undefined, document.getElementById(divId));
	}
});
```

Caveats: You'll have to manually create the div for each slide and give it a unique ID instead of using the RemarkJS dot-div syntax:

 `<div class="mermaid" id="diagram1">..mermaid code..</div>`

Add a slide property `mermaid: diagram1`

A little CSS magic to get things centered within the display area. You will have to adjust for your sized slides:

```
.mermaid { width: 780px; }
.mermaid svg {
  display: block;
  margin: auto;
  max-width: 780px;
}
```
One final caveat, since the JS only fires off on slide change, if you reload the page on a slide with Mermaid syntax, you will not see it render. You must navigate away then back.

**Comment by knsv** [comment]
@utdrmac nice one!

It is possible to tweak this slightly so that the ids can be avoided. I have not tested this in all browsers but in Chrome at least this works:
```
      slideshow.on('afterShowSlide', function(s) {
          var diagrams = document.querySelectorAll('.mermaid');
          var i;
          for(i=0;i<elems.length;i++){
            if(diagrams[i].offsetWidth>0){
              mermaid.init(undefined, diagrams[i]);
            }
          }
      });
```

The caveat also remains ofc. Maybe this should be document in the Remark wiki...

**Comment by utdrmac** [comment]
Yea, I got it working but abandoned Mermaid integration because I couldn't get Mermaid to draw boxes the way I needed them. When attempting to draw a simple 3-level B-Tree (7 total nodes), the 2 nodes on level 1 would not align horizontally. I couldn't find any CSS tricks or documentation that would constrain or "force" horizontal/vertical alignment.

**Comment by geirsagberg** [comment]
I added a snippet to initalize mermaid for the current slide (if reloading on a slide with a graph, e.g.):

```javascript
var slideshow = remark.create({
  ratio: '16:9',
  highlightStyle: 'monokai',
  highlightLanguage: 'javascript'
});
mermaid.initialize({
  startOnLoad: false,
  cloneCssStyles: false
});
function initMermaid(s) {
  var diagrams = document.querySelectorAll('.mermaid');
  var i;
  for(i=0;i<diagrams.length;i++){
    if(diagrams[i].offsetWidth>0){
      mermaid.init(undefined, diagrams[i]);
    }
  }
}
slideshow.on('afterShowSlide', initMermaid);
initMermaid(slideshow.getSlides()[slideshow.getCurrentSlideIndex()]);
```

**Comment by kuulemart** [comment]
@geirsagberg How this code is supposed to work? Maybe I'm missing something but initMermaid function does not use it's input parameter s.

**Comment by geirsagberg** [comment]
Not sure, that was 6 months ago ;-) there is probably a better way to do it, but it worked for me.

**Comment by nmaro** [comment]
Here is my solution:

```
slideshow.on("afterShowSlide", s => {
  const [slide] = document.getElementsByClassName("remark-visible");
  mermaid.init(Array.from(slide.getElementsByClassName("mermaid")));
});
```
