### ISSUE TITLE
TypeError: Cannot read property 'layout' of undefined

### ISSUE THREAD

**Issue by ankurp** [knsv/mermaid#37]
Error at this expression `require("./dagre").layout;` when loading the full mermaid script from dist folder of this github project.

**Comment by knsv** [comment]
@ankurp: Is still problem for you?

**Comment by ankurp** [comment]
@knsv I haven't tried but will let you know when I do next time.

**Comment by bollwyvl** [comment]
To recap from #127: the [IPython/Jupyter notebook](http://ipython.org/notebook.html) would be a wonderful place to use mermaid. Its frontend has markdown as a first-class citizen, so hand editing would already be very natural... and it would be easy to generate mermaid DSL from any number of the supported backends. Sadly, we encounter the dagre.layout issue: here are my explorations of the kinds of errors:
http://nbviewer.ipython.org/gist/bollwyvl/7b4729c21b3d1ad4c31e

Aside from the dagre error, some things appear to be broken around `he` and `lodash`.

There is no option to not have require, or change the order in which things load, and punting to an iframe is pretty much unacceptable. So let's solve this thing.

I'd love to pitch in trying to solve this. As i mention on the dupe, there could be some [build options](http://stackoverflow.com/questions/25999947/how-to-solve-a-conflict-between-browserify-backbone-based-app-and-require-js-o) that might just solve this, or it may be appropriate to create a separate AMD build.

**Comment by knsv** [comment]
@bollwyvl, thanks for your effort. Help is always welcome!

I tested loading mermaid using requirejs and could replicate the TypeError. After some reading I found that require creates a define method that confuses the package created by browserify. To handle that I have wrapped mermaid so that the requires define function remains undefined in mermaids context. For my test page this removed the error. I will commit the fix and would appreciate if you could try it in your context before release.

**Comment by bollwyvl** [comment]
I think we have a winner, at least for nbviewer:
http://nbviewer.ipython.org/gist/bollwyvl/d5a120156216797c7132

That will render two separate embedded mermaid figures. Great!

Thanks so much @knsv!

A few remaining issues:
- Looks like the IPython notebook (and likely many other sites) will claim many of the classes that are in use. The one that jumps out at me is `label`, which bootstrap claims. `node`, `path` is something else.
- when editing, i am naively calling `mermaid.init()` every time now, which doesn't work very well... ids get reused, dogs and cats are living together. mass hysteria. 
  - Some better access to what gets rendered would be fabulous: perhaps a second argument to init could be an element, node list or selector that would get used, 
  - ...as well as a persistent counter for indices that will never repeat:

```js
var init = function (sequenceConfig, arr) {
  arr = arr == null ? document.querySelectorAll('.mermaid')
    : typeof arr === "string" ? document.querySelectorAll(arr)
    : arr instanceof Node ? [arr]
    : arr;
...
  var id = 'mermaidChart' + mermaid.nextIdx++;
...
```

Looking good already, though!

**Comment by bollwyvl** [comment]
Actually just tried that hack out: works great!
https://gist.github.com/bollwyvl/53e64cdafba38461943b
(sorry, but I don't have a build environment handy... will happily raise a PR if you like)

Here is a notebook that uses it:
http://nbviewer.ipython.org/gist/bollwyvl/e51b4e724f0b82669c84

If you look at the source, you'll see that there are no dirty tricks, like embedding the output:
https://gist.github.com/bollwyvl/e51b4e724f0b82669c84

Note that you can try out the whole shebang by downloading the ipynb file up there, and dragging into the tree page you get when you hit http://tmpnb.org

I've added a touch of CSS to make it visible in the bootstrap environment.

Note that it is still breaking things, with the `mismatched anonymous define` error. Perhaps in browserify, one of the deglobalify/deamdify filters would keep this from leaking out into the require scope.

**Comment by bollwyvl** [comment]
Ha, I didn't even circle back and try the original failing approaches. Mermaid as of f4b2211 can be directly loaded with require:
```javascript
require(["./wherever/is/mermaid.full.js"], function(d3){ mermaid.init(); });
```
I would say that that closes the issue, as it *works* now, even if it is slightly outside what a requirejs user would expect: it still installs itself on `window.mermaid`, as opposed to returning a reference to itself... weirdly, you get back the bundled d3, which is likely not the desired effect, but that's a different issue.

As to its integration into IPython (_my_ original goal): here is a working notebook that uses require to both do an initial draw (as on nbviewer) as well as the live-editing:
http://nbviewer.ipython.org/gist/bollwyvl/e160958fdc8656dc8d3d

The only error now is because the actual editor scripts are not available in nbviewer, but this is fine!

I'll raise separate PRs for my hacks!

**Comment by bollwyvl** [comment]
Also #134.

**Comment by knsv** [comment]
I am going though the issues and compiling a roadmap. Is this still an issue or can I close it? @ankurp @bollwyvl

**Comment by bollwyvl** [comment]
I think this is solved with the umd stuff.

**Comment by knsv** [comment]
OK, will close then. Thx!
