### ISSUE TITLE
Put your own action on the chart

### ISSUE THREAD

**Issue by yhjhoo** [knsv/mermaid#372]
Hi 

Is it possible to put your own JavaScript action on the chart? Eg: click on start icon, trigger a ajax call.

**Comment by tylerlong** [comment]
Yes, please read https://mermaidjs.github.io/flowchart.html and find the section "Interaction".

**Comment by dfederighi** [comment]
Tyler ... I wrote an email, but maybe it's easier here. Does this action/interaction work or will it work with Gantt charts?

**Comment by SgtPooki** [comment]
> Yes, please read https://mermaidjs.github.io/flowchart.html and find the section "Interaction".

The link is broken; https://mermaidjs.github.io/#/flowchart?id=interaction seems like the proper link now.

**Comment by Dunning-Kruger** [comment]
@SgtPooki Hey, it seems like you're answering to a year and a half old issue/question. Feel free to open a new issue if you need any assistance. I'll lock this issue soon.

**Comment by SgtPooki** [comment]
@Dunning-Kruger I was just updating the documentation since the info in this issue was no longer valid. I don't have a particular issue, but there is a bug with the click event. thanks for the quick response :)

**Comment by Dunning-Kruger** [comment]
@SgtPooki  I appreciate the intention but issues are not an authoritative source of information. The link was valid at the time this issue was open and that is enough. Otherwise, we'd have a full-time job of keeping the ever-growing list of closed issues updated, or be flooded by notifications of comments "updating" closed issues. 

As for the "bug with the click event", in case you're not talking about #891, feel free to create a new issue with the repro and we'd be happy to take a look!
