### ISSUE TITLE
New line at the end of SVG file

### ISSUE THREAD

**Issue by joelrfcosta** [knsv/mermaid#400]
GitHub review is warning that there should be an empty line at the end of document:

<img width="549" alt="screen shot 2016-10-17 at 10 12 34" src="https://cloud.githubusercontent.com/assets/1642586/19431969/75263538-9452-11e6-8dba-6053427f6d9e.png">

Is this reasonable, or just does not make sense on this document type?

**Comment by nicksp** [comment]
@joelrfcosta This is reasonable imo. The message is displayed because otherwise there is no way to tell the difference between a file where there is a newline at the end and one where is not. Diff has to output a newline anyway, or the result would be harder to read or process automatically.
And make sure, we have setting in `.editorconfig` that force us to use newlines. 

This is a good habit to have newlines at the end of files due to [1](http://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file) and [2](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) btw

**Comment by knsv** [comment]
I am guessing that the use case is a svg generated by the cli with svg option set. Correct?

**Comment by joelrfcosta** [comment]
Correct! 👍

**Comment by knsv** [comment]
Found the right place in the code to fix this but unsure about how to handle this in a platform independent way.

**Comment by knsv** [comment]
Closed by release 7.0.0, please reopen if issues remain.
