### ISSUE TITLE
Live editor sticky sidebar

### ISSUE THREAD

**Issue by orschiro** [knsv/mermaid#414]
Dear all, 

Can we make the sidebar of the live editor sticky upon scroll down to always be able to edit the code, even when looking at a section at the bottom of the rendered flow chart?

![image](https://cloud.githubusercontent.com/assets/170947/20624213/f000f98c-b30b-11e6-86a6-e904767ea3dd.png)

**Comment by tylerlong** [comment]
Most of the time we don't have such a long chart.

And you can change the chart from vertical to horizontal (and change it back before you publish your chart): https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggUkwKQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpCkIgLS0-IEN7TGV0IG1lIHRoaW5rfQpDIC0tPnxPbmV8IERbTGFwdG9wXQpDIC0tPnxUd298IEVbaVBob25lXQpDIC0tPnxUaHJlZXwgRltDYXJdCg

So for now I will mark this issue as won't fix.


## A vertical chart from right to left

![image](https://user-images.githubusercontent.com/733544/30508494-ae8547f4-9aca-11e7-9ae3-463547d80514.png)

**Comment by tylerlong** [comment]
Finally I decided to implement this feature because it is quite simple.

Have a try and enjoy! :)

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpCkIgLS0-IEN7TGV0IG1lIHRoaW5rfQpDIC0tPnxPbmV8IERbTGFwdG9wXQpDIC0tPnxUd298IEVbaVBob25lXQpDIC0tPnxUaHJlZXwgRltDYXJdCkYgLS0-IEcKRyAtLT4gSApIIC0tPiBJCkkgLS0-IEoKSiAtLT4gSwpLIC0tPiBMCkwgLS0-IE0KTSAtLT4gTgpOIC0tPiBPCk8gLS0-IFAKUCAtLT4gUQpRIC0tPiBSClIgLS0-IFMKUyAtLT4gVA
