### ISSUE TITLE
mermaid.init() on hidden items is not displaying labels

### ISSUE THREAD

**Issue by weasteam** [knsv/mermaid#444]
When mermaid.init() was called and the hidden items (they were placed in a collapsible body and hide on default) did not display the label correctly, see the picture bellow (very appreciate for any solutions or bug fix):

![screen shot 2016-12-29 at 1 39 03 am](https://cloud.githubusercontent.com/assets/6238854/21540940/c05ef028-cd67-11e6-818c-f4d726f77ef4.png)

**Comment by whyzdev** [comment]
Hi, 
which browser are you using? Looks like this not from command-line. 
are you using the latest mermaid? what's your html and css looks like? 
It's likely browser/css issue. i cannot reproduce it. so asking.
Thanks!

**Comment by whyzdev** [comment]
Thanks. I can see it now, with the above sample html and a <script> section to call mermaid.initialize(config). The width the height of label and rect in collapsible section are incorrect. So once expanded, it doesn't display correctly.  

I will play with it to see if anything mermaid can do better for the case. 

Or maybe workaround exists by making all section expanded but somehow invisible. Then after initialized, collapse them and/or make one section active.

**Comment by niksfirefly** [comment]
not working with bootstrap 3 tabs also
same efffect

**Comment by prtuson** [comment]
I managed to get this working for a mermaid flow diagram not of the first tab.
The code is here:
	<script type="text/javascript">
		jQuery(document).ready(function () {
			var config = {startOnLoad:false, cloneCssStyles:false, leftMargin: 0, logLevel: 1, flowchart:{useMaxWidth:false, htmlLabels:true}};
	       		mermaid.initialize(config);
		});
		jQuery(document).on('click', '[href*="etTher"]',  function () {
	       		mermaid.initialize({startOnLoad:true});
			mermaid.init();
		});
	</script>

Mermaid starts on load anyway, so I set start on load to false. I turned on logging so that I could see what it was doing.
I then set up a click event on the tab that contained the mermaid drawing. So when the tab was clicked then I set mermaid back to start on load true. I then found that I had to call mermaid.init() to finish off the drawing - it now works fine.

My plan if I have a mermaid drawing on more than 1 tab is to change the class of the div to something other than mermaid and then change it to mermaid as the first action when clicking on the tab.
