### ISSUE TITLE
Flowchart edge labels placement

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [knsv/mermaid#490]
The placement of edge labels in flowcharts is unfortunate. For example:

    graph TD
      A---|This is the text|B;

From the examples of the [website](https://knsv.github.io/mermaid/live_editor/) already writes the text on the edge, instead of next to it. In horizontal flowcharts this is even worse and makes the text look like stroke through. On the other hand in sequence diagrams the text is at least placed above the edges, which is already an improvement. Desirable would be some integrated logic, which tries to avoid lines going over the the texts of labels and/or text, which breaks in an optimal way, so that it is not crossed by edges or nodes.

This might be difficult to implement, but is crucial to pretty diagrams.

**Comment by Rektis** [comment]
The manual shows that labels have a background colour. This would allow placement directly on the edge.

Judging by the changelog, this got broken before 7.0 and is fixed since then, but it still doesn't work in the live editor:
https://knsv.github.io/mermaid/live_editor/
Maybe the live editor is using an older version? I exclusively use the live editor to quickly make some diagrams. It'd be great if it could be updated.

**Comment by tylerlong** [comment]
I think it has been fixed.

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKICBBLS0tfFRoaXMgaXMgdGhlIHRleHR8QjsK

Feel free to reopen if you still have this issue.

**Comment by Rektis** [comment]
It seems to work now.

Thank you so much!
