### ISSUE TITLE
Arrow heads missing (cli, 7.0.3)

### ISSUE THREAD

**Issue by asgoth** [knsv/mermaid#544]
Arrow heads are missing, when using the cli (version 7.0.3).

Last version which worked: 7.0.0

Test case:

    graph TD
        A --> B
        B -.-> C

Which results in the following image:

![bug mmd](https://user-images.githubusercontent.com/2804402/27283083-f6e168c0-54f2-11e7-923b-38b08c7067a5.png)

Cli arguments used:

    "mermaid": "mermaid documentation/resources/*.mmd --phantomPath node_modules/.bin/phantomjs --outputDir documentation/resources -w 400",

**Comment by tylerlong** [comment]
I tested the web version and it seemed OK. So this problem is probably a cli specific issue.

**Comment by K4zuki** [comment]
I am facing same, arrow heads missing

seems it only happens on flowchart.
from repo top README only this one does not work as expected:
```
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

---

- ubuntu 16.04
- nodejs 4.2.6
- mermaid(from `npm`) 7.0.3

**Comment by MartB** [comment]
Confirmed broken with multiple of my diagrams.
Any eta for a fix or a pointer on where this got introduced ?

**Comment by tylerlong** [comment]
Could anybody confirm: does version 7.0.0 has this issue or not?

**Comment by K4zuki** [comment]
@tylerlong 
`7.0.0` worked on Mac

**Comment by tylerlong** [comment]
I upgraded the library from 7.0.0 to 7.0.3. I didn't change any major logic. One possible reason might be I upgraded phantomjs to latest version.

I will definitely take a look. Maybe we will replace phantomjs with headless Chrome. For now, please stick to 7.0.0. Because 7.0.3 adds no new feature (major change is webpack support added)

**Comment by wangnangg** [comment]
Looking at the generated SVG, it seems that the reference of the arrow head definition is not  correct.
It should be "url(#arrowhead)" instead of "url(about:blank #arrowhead)" . Hope this helps.

**Comment by tylerlong** [comment]
I am sorry I have been busy with my daily job. Now I am back to the mermaid development. 

I just did a quick test in the live editor: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKICAgIEEgLS0+IEIKICAgIEIgLS4tPiBDCg==

![image](https://user-images.githubusercontent.com/733544/29372419-9f794e4a-82dd-11e7-99d1-8274069756ce.png)

There is not problem. So I think this is a CLI only issue and it is most likely caused by PhantomJS.

PhantomJS is discontinued: http://carstenwindler.de/software-testing/phantomjs-is-discontinued/

Here is my plans:

1. Try to fix the issue with PhantomJS
2. If #1 doesn't work, investigate jsdom: https://github.com/knsv/mermaid/issues/559

**Comment by GTB3NW** [comment]
tylerlong, headless chromium is also an option now.

**Comment by KeenS** [comment]
I faced the same issue on both the [Demo](https://mermaidjs.github.io/demos.html) page and [Online Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/c2VxdWVuY2VEaWFncmFtCiAgICBBbGljZSAtPj4gQm9iOiBIZWxsbyBCb2IsIGhvdyBhcmUgeW91PwogICAgQm9iLS0+PkpvaG46IEhvdyBhYm91dCB5b3UgSm9obj8KICAgIEJvYi0teCBBbGljZTogSSBhbSBnb29kIHRoYW5rcyEKICAgIEJvYi14IEpvaG46IEkgYW0gZ29vZCB0aGFua3MhCiAgICBOb3RlIHJpZ2h0IG9mIEpvaG46IEJvYiB0aGlua3MgYSBsb25nPGJyLz5sb25nIHRpbWUsIHNvIGxvbmc8YnIvPnRoYXQgdGhlIHRleHQgZG9lczxici8+bm90IGZpdCBvbiBhIHJvdy4KCiAgICBCb2ItLT5BbGljZTogQ2hlY2tpbmcgd2l0aCBKb2huLi4uCiAgICBBbGljZS0+Sm9objogWWVzLi4uIEpvaG4sIGhvdyBhcmUgeW91Pwo=)

Arrow heads of the last 2 lines are missing

![image](https://user-images.githubusercontent.com/4434568/29746501-52f0f310-8b17-11e7-96dc-7ce82b1398a9.png)

And when I inspect it, arrow heads aren't even in SVG tree

![image](https://user-images.githubusercontent.com/4434568/29746519-af2aab1c-8b17-11e7-9e99-74a349c21b08.png)


Note: I'm using Firefox 55 on Linux

**Comment by tylerlong** [comment]
@KeenS 

It is by design: https://mermaidjs.github.io/sequenceDiagram.html

Type | Description
-- | --
-> | Solid line **without** arrow
--> | Dotted line **without** arrow
->> | Solid line with arrowhead
-->> | Dotted line with arrowhead
-x | Solid line with a cross at the end (async)
--x | Dotted line with a cross at the end (async)

**Comment by KeenS** [comment]
@tylerlong I'm sorry and thank you for telling me the documentation. I missed it.

**Comment by dslztx** [comment]
My solution is as follows:
```
sudo npm install mermaid@7.0.0 -g 
sudo npm install phantomjs@2.1.1 -g 
```
By the way,there not exist double sided arrow markup in flowchar,is it right?

**Comment by tylerlong** [comment]
Guys, sorry for the delay. 

Please check this project: https://github.com/mermaidjs/mermaid.cli

I want to move CLI out of mermaid main project in the near future.

It's new so there might be bugs. Its code is deadly simple so everyone here can contribute:  https://github.com/mermaidjs/mermaid.cli/blob/master/index.js

I will keep this issue open till the end of this week. Please reply if you still have issues.
