### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by ylq167** [knsv/mermaid#557]
![](http://oizi4nn30.bkt.clouddn.com//20170808172215_JP0O0w_bug.jpeg)

Please fix it.
thanks.

**Comment by ylq167** [comment]
```

gantt
        dateFormat  YYYY-MM-DD
        title Adding GANTT diagram functionality to mermaid
        section A section
        Completed task            :2014-01-06, 2d
        Active task               :2014-01-09, 3d
        Future task               :2014-01-11, 2d
        
```

**Comment by ylq167** [comment]
Something wrong in Time axis.

**Comment by tylerlong** [comment]
Could you please be more specific? What is the bug?

Here is the diagram in live editor: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z2FudHQKICAgICAgICBkYXRlRm9ybWF0ICBZWVlZLU1NLURECiAgICAgICAgdGl0bGUgQWRkaW5nIEdBTlRUIGRpYWdyYW0gZnVuY3Rpb25hbGl0eSB0byBtZXJtYWlkCiAgICAgICAgc2VjdGlvbiBBIHNlY3Rpb24KICAgICAgICBDb21wbGV0ZWQgdGFzayAgICAgICAgICAgIDoyMDE0LTAxLTA2LCAyZAogICAgICAgIEFjdGl2ZSB0YXNrICAgICAgICAgICAgICAgOjIwMTQtMDEtMDksIDNkCiAgICAgICAgRnV0dXJlIHRhc2sgICAgICAgICAgICAgICA6MjAxNC0wMS0xMSwgMmQ=

**Comment by ylq167** [comment]
@tylerlong 中文说了哦～你看图里时间横轴的区间不能正常显示呀。显示的都是 2014，在最后才显示出月／日。

**Comment by tylerlong** [comment]
But your screenshot doesn't demonstrate the issue.  The x-axis part in your screenshot is just transparent/blank. Could you please take a new screenshot?


![image](https://user-images.githubusercontent.com/733544/29594493-f8eb8582-87e3-11e7-9208-48b2e9dd6d30.png)

In the screenshot above we can see the x-axis. But there is only week, no year. Is it what you are reporting?

**Comment by tylerlong** [comment]
I can reproduce the issue here http://mdp.tylingsoft.com/

**Comment by ylq167** [comment]
ok.
![](http://oizi4nn30.bkt.clouddn.com//20170823113430_7ElSN5_bug.jpeg)

**Comment by tylerlong** [comment]
It has something to do with gantt diagram time formatting config. I will investigate when I have some time.

**Comment by tylerlong** [comment]
I think the issue has been fixed:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z2FudHQKICAgICAgICBkYXRlRm9ybWF0ICBZWVlZLU1NLURECiAgICAgICAgYXhpc0Zvcm1hdCAlbS0lZAogICAgICAgIHRpdGxlIEFkZGluZyBHQU5UVCBkaWFncmFtIGZ1bmN0aW9uYWxpdHkgdG8gbWVybWFpZCAoWWVhciAyMDE0KQogICAgICAgIHNlY3Rpb24gQSBzZWN0aW9uCiAgICAgICAgQ29tcGxldGVkIHRhc2sgICAgICAgICAgICA6MjAxNC0wMS0wNiwgMmQKICAgICAgICBBY3RpdmUgdGFzayAgICAgICAgICAgICAgIDoyMDE0LTAxLTA5LCAzZAogICAgICAgIEZ1dHVyZSB0YXNrICAgICAgICAgICAgICAgOjIwMTQtMDEtMTEsIDJk

Now you can specify the format of axis:  https://github.com/knsv/mermaid/issues/269#issuecomment-373229136

I formatted it without year because it will make the display too crowed. And I add the year to the title. I hope it makes sense to you.

I haven't update the markdown plus project.
