### ISSUE TITLE
Styling: classes aren't applied to elements.

### ISSUE THREAD

**Issue by joostas** [knsv/mermaid#582]
Styling: classDef and classes aren't applied to elements. 
Example:
```mermaid
graph TD
A-->B
C-->D
classDef def fill:#00f
class A def
```

Element A is green, but should be blue.

**Comment by BiteBit** [comment]
I have the some issue.

**Comment by aaroncalderon** [comment]
It's weird, because the [demo: Larger flowchart with some styling](https://mermaidjs.github.io/demos.html) works, but it does not when I try the same thing on the [live editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEIKICAgIHNxW1NxdWFyZSBzaGFwZV0gLS0-IGNpKChDaXJjbGUgc2hhcGUpKQoKICAgIHN1YmdyYXBoIEEgc3ViZ3JhcGgKICAgICAgICBvZD5PZGQgc2hhcGVdLS0gVHdvIGxpbmU8YnIvPmVkZ2UgY29tbWVudCAtLT4gcm8KICAgICAgICBkaXtEaWFtb25kIHdpdGggPGJyLz4gbGluZSBicmVha30gLS4tPiBybyhSb3VuZGVkPGJyPnNxdWFyZTxicj5zaGFwZSkKICAgICAgICBkaT09PnJvMihSb3VuZGVkIHNxdWFyZSBzaGFwZSkKICAgIGVuZAoKICAgICUlIE5vdGljZSB0aGF0IG5vIHRleHQgaW4gc2hhcGUgYXJlIGFkZGVkIGhlcmUgaW5zdGVhZCB0aGF0IGlzIGFwcGVuZGVkIGZ1cnRoZXIgZG93bgogICAgZSAtLT4gb2QzPlJlYWxseSBsb25nIHRleHQgd2l0aCBsaW5lYnJlYWs8YnI-aW4gYW4gT2RkIHNoYXBlXQoKICAgICUlIENvbW1lbnRzIGFmdGVyIGRvdWJsZSBwZXJjZW50IHNpZ25zCiAgICBlKChJbm5lciAvIGNpcmNsZTxicj5hbmQgc29tZSBvZGQgPGJyPnNwZWNpYWwgY2hhcmFjdGVycykpIC0tPiBmKCwuPyErLSrYsikKCiAgICBjeXJbQ3lyaWxsaWNdLS0-Y3lyMigoQ2lyY2xlIHNoYXBlINCd0LDRh9Cw0LvQvikpOwoKICAgICBjbGFzc0RlZiBncmVlbiBmaWxsOiM5ZjYsc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjJweDsKICAgICBjbGFzc0RlZiBvcmFuZ2UgZmlsbDojZjk2LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDo0cHg7CiAgICAgY2xhc3Mgc3EsZSBncmVlbgogICAgIGNsYXNzIGRpIG9yYW5nZQ).

Any Ideas?

**Comment by marceloboeira** [comment]
@aaroncalderon same here...

**Comment by pierrebonbon** [comment]
Same here. I am being able to style each node individually:

![screenshot_2](https://user-images.githubusercontent.com/11869768/36801688-ac09c88a-1caa-11e8-8e6f-96c2420aff77.jpg)

But when I try doing it with `classDef` nothing happens:

![screenshot_1](https://user-images.githubusercontent.com/11869768/36801696-b40f505e-1caa-11e8-8fac-33ababeb65ae.jpg)

**Comment by cryodream** [comment]
I spent hours trying to get this to work in VS Code.
Hope it'll get fixed, because defining styles individually is a pita.

**Comment by calve** [comment]
Same here. Looking at the generated HTML, nodes do get classes attributes, but I cannot find any css rules matching the class, nor find any occurence of my classname in the generated document. I believe there is a bug preventing the CSS rules to be set.

This regression seems to appear between releases 7.0.14 and 7.0.15  which lead me to commit 72493b7a8b0edc45b53884b443d690a9e68d8e1a.

```
   graph TD

     hello --> world;
     classDef someclass fill:#f96;
     class hello someclass;
```
Please note that the ordering do matter. Also this is processed by sphinx-mermaid but this is not relevant here.

Before (7.0.14)  ![screenshot_20180305_204032](https://user-images.githubusercontent.com/4311079/36995808-6c83a64a-20b5-11e8-8944-4797748fa0ad.png)


After (7.0.15) ![screenshot_20180305_202955](https://user-images.githubusercontent.com/4311079/36995285-f02eeb32-20b3-11e8-829e-5f6bc3d80de0.png)



 @tylerlong would be glad if you could shed us some light on this ? :upside_down_face:

**Comment by tylerlong** [comment]
Hi guys, I am here. I will take a look tonight.

@calve  thank you for figuring out the commit which brought this regression.

**Comment by tylerlong** [comment]
Fixed: https://github.com/knsv/mermaid/compare/a8e49a0d2d522d7fb880b31b86453560f41b5653...0d0f793f8147e473ce082c18eeced2d806725db1

![image](https://user-images.githubusercontent.com/733544/37406756-de26dfd2-27d2-11e8-945c-7676f97f3891.png)

**Comment by marceloboeira** [comment]
@tylerlong thanks!

**Comment by LeDuble** [comment]
@tylerlong thank you!
