### ISSUE TITLE
Just wanted to say : THANKS !

### ISSUE THREAD

**Issue by cavo789** [knsv/mermaid#618]
Hi Knut and other contributors, 

Just wanted to say: thank you! I'm doing more and more with markdown and your library is just great! 

So easy to use...

_Perhaps one suggestion (no doubt someone has already mentioned it): if, from within the browser, we make a selection (f.i. CTRL-A for select all) and copy the result in, for instance, a mail body, we're losing the chart. Probably should we first export it using Pandoc (not yet tried) but in that case it's quite "complex" (we need to first install Pandoc then install converters and so on...).
I fully understand it's just JS and CSS representation (and it's really a tremendous job!) but, yeah, it's a little annoying to not being able to copy/paste the rendering outside the browser and lose it._

So, thank you guys for this nice job ! 🥇

**Comment by tylerlong** [comment]
Lot of people are having issue copying svg images, not just us:

https://stackoverflow.com/questions/12255444/copy-svg-images-from-browser-to-clipboard

**Comment by Apachez-** [comment]
I want to join in on the THANKS!

I have been looking for a tool to quick and easy create network maps (from textfiles since Im tired of spending hours of redesigning existing maps through visio and other gui based tools) and even if current version of mermaid doesnt fulfill all my needs (created separate issues on this) the learning curve to start using mermaid (for network mapping) is far easier than for example graphviz.
