### ISSUE TITLE
Generate deterministic output

### ISSUE THREAD

**Issue by colega** [knsv/mermaid#727]
Since we're using the current date for `id`s of the graphs in the SVG output, we can't generate a deterministic output and thus we can't use automated tools to check whether those graph have changed (by just `diff`ing the output)

It was changed here: https://github.com/knsv/mermaid/commit/5b6dfb01a6a3d458893c71249b9e9e7c5a911140 
Is there any specific reason to do that? Can we revert that commit or find any other solution? Maybe make this configurable?

**Comment by kimble** [comment]
I'm also in favor of reverting that commit. We store documentation in git and the date id obviously causes all the diagrams to change every single time someone updates to doc.

**Comment by sindre-nistad** [comment]
As a side, the ID could start at some pseudorandom point, determined by the user, or the Base64 string that is given.

**Comment by bgschiller** [comment]
This is also causing headaches for me.

**Comment by sindre-nistad** [comment]
Would it be possible to reopen this issue, @knsv?

**Comment by bgschiller** [comment]
fwiw, I've implemented a workaround for my own use-case. I'm using remark-mermaid to generate images from mermaid markup inside a markdown file. Each file is named according to the hash of the markup, so the filename is consistent. But the contents change (because of the use of `Date.now()` for making ids). In order to both

1. remove files that are no longer referenced, and
2. avoid spurious changes when only the ids have changed.

I do the following:

```bash
find images | grep -E '[0-9a-f]+\\.svg' | xargs rm && # delete all mermaid images
remark . -o && # extract mermaid docs from .md files, write them to images dir.
# finally, identify svg files that were only modified, not deleted, and restore their earlier version.
 git status -s | grep -E '[0-9a-f]+\\.svg' | grep '\\bM\\b' | cut -d' ' -f 3 | xargs git restore
```

This relies on the fact that the filename of each svg is based on the content of the mermaid source, and not the content of the svg.

**Comment by julianbei** [comment]
I have added a PR here: https://github.com/mermaid-js/mermaid/pull/1787

Please give some feedback. The `Date.now()` Ids are getting annoying in our setup where prior to each release an SVG is generated and checked into git. 
Right now the SVG needs to be overwritten every time. 

So I added this feature PR.
