### ISSUE TITLE
Node erroneously inside subgraph

### ISSUE THREAD

**Issue by KevinSnyderCodes** [knsv/mermaid#738]
Using 8.0.0-rc8

```
graph TD
subgraph s
A-->B
end
B
```

Expected output: B is not part of subgraph s

Actual output: B is part of subgraph s

Example: https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbnN1YmdyYXBoIHNcbkEtLT5CXG5lbmRcbkIiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

I would expect node B to be outside subgraph s because it is "defined" outside of the subgraph scope, even though it is first encountered inside the subgraph scope.

**Comment by afandian** [comment]
I just came to post the same thing. Appears to haappen when B is mentined in a subgraph. Here's my example:

```
graph LR;
  aa;
  bb;

  subgraph xyz
    xx;
    aa --> xx;
  end
```

https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggTFI7XG4gIGFhO1xuICBiYjtcblxuICBzdWJncmFwaCB4eXpcbiAgICB4eDtcbiAgICBhYSAtLT4geHg7XG4gIGVuZCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

It looks like it is possible to have nodes outside subgraphs, but only if they never link to anything!

A workaround is to put the arrow outside of the graph, but that doens't seem right. 

```
graph LR;
  aa;
  aa --> xx;
  bb;

  subgraph xyz
    xx;

  end
```

I don't know the codebase but my guess is that the bug is in the functions that create nodes from arrows when they reference undeclared nodes. Nodes are implicitly created in the subgraph context, even though they have been declared to exist elsewhere.

**Comment by GDFaber** [comment]
> graph TD
> subgraph s
> A-->B
> end
> B

The problem is that by defining a connection to a new node you also define the node itself. Therefor it is situated inside the subgraph instead of being separate as intended. A possible solution would be to define the nodes first and connect them afterwards, for example:

`graph TD`
`subgraph s`
`A`
`end`
`B`
`A-->B`
