### ISSUE TITLE
Where to get mermaid.min.css from when installing from npm?

### ISSUE THREAD

**Issue by laurent22** [knsv/mermaid#797]
I'm trying to add Mermaid support to an Electon application. I managed to load the JS library and render some diagrams, however some parts of them are missing and I think it's due to missing CSS.

However I cannot figure out where the CSS for Mermaid is. When I do `npm install mermaid`, there are some JS files in /dist but no CSS. The doc simply give this as an example:

```
<link rel="stylesheet" href="mermaid.min.css">
```

So I'm wondering where can I get this mermaid.min.css file from?

**Comment by Beefy-Swain** [comment]
+1

**Comment by nomadhermit** [comment]
Looks like the approach to CSS may have changed, but not fully documented in latest version?  issue #642 is still open requesting help updating documentation for Mermaid 8.0 from contributors.
I found this searching for CSS in the online documentation which appears to explain the missing mermaid.min.css file:  
https://mermaidjs.github.io/breakingChanges.html 
which states the following:
```
#2

In old versions you need to add CSS file to your HTML:

<link rel="stylesheet" href="mermaid.min.css">

or

<link rel="stylesheet" href="mermaid.forest.min.css">

Now it is not needed to do so. And there are no more CSS files in distrubtion files.

You just

mermaid.initialize({
    theme: 'forest'
})

and it works like a charm.

This is because now the CSS is inline with SVG for portability.
```

Looks like "forest", the text used to reference the example theme,  shows up in two files 
 src/mermaidAPI.js
 dist/index.html
based on the following search:
https://github.com/knsv/mermaid/search?q=forest&unscoped_q=forest

**Comment by MatinF** [comment]
I tried to follow the above in order to customize the styling within my Jekyll docs with this plugin. However, I seem unable to get the following part to work:

```
mermaid.initialize({
    theme: 'forest'
})
```

Where would you specifically insert this in a Jekyll docs project?

Also, if I want to customize my own CSS with full control, would I add a local stylesheet and refer to this in the header? It seems to me that when I attempt to do this, the styles I use are overwritten by those "hardcoded" into the mermaid js file in my assets folder.

Any inputs would be highly appreciated,
Martin

**Comment by laurent22** [comment]
This is still not fixed. The documentation refers to a "mermaid.min.css" which is nowhere to be found.
