### ISSUE TITLE
found 1 high severity vulnerability

### ISSUE THREAD

**Issue by Vanessa219** [knsv/mermaid#839]
![image](https://user-images.githubusercontent.com/970828/57747030-4f922e00-7706-11e9-86e3-a643f8fe0b2b.png)

**Comment by NicolaiSoeborg** [comment]
Link: https://www.npmjs.com/advisories/751

**Exploit:**
All versions of mermaid are vulnerable to Cross-Site Scripting. If malicious input such as `A["<img src=invalid onerror=alert('XSS')></img>"]` is provided to the application, it will execute the code instead of rendering it as text due to improper output encoding.

**Comment by IOrlandoni** [comment]
This is being handled on #847.
