### ISSUE TITLE
Format text

### ISSUE THREAD

**Issue by g3blv** [knsv/mermaid#924]
Is it possible to format text? I haven't found anything in the documentation. I would like to make text *italic*, **bold** and `code`. Maybe the same conventions like in markdown could be used where the text is enclosed by *, ** and ` to mark text that should be formatted as italic, bold and code

**Comment by spbert29** [comment]
You can add a class like [this](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5jbGFzc0RlZiB0ZXN0IGZpbGw6bGlnaHRibHVlLGNvbG9yOmdyZWVuLHN0cm9rZTojRkY5RTJDLGZvbnQtd2VpZ2h0OmJvbGQgXG5jbGFzcyBBIHRlc3QiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ):

[Here ](https://mermaidjs.github.io/#/flowchart?id=styling-and-classes)you can find the man

**Comment by g3blv** [comment]
@spbert29  Thx. Is it possible to specify the class for part of the string rather than the whole string? Something l like `B(Go <div class = "test">shopping</div>)` with the following result "Go **shopping**"

**Comment by spbert29** [comment]
As far as i see, it is not really possible. Everything where you have to add quotes(single or double doesnt matter, it seems like mermaid allways uses double quotes in the background) will fail because it will break the syntax. 
![image](https://user-images.githubusercontent.com/42182294/64261250-83e75f80-cf2c-11e9-90f5-0762fe031105.png)

But you can add html tags like `<b>` tag for example:
![image](https://user-images.githubusercontent.com/42182294/64261507-ee989b00-cf2c-11e9-8fb6-04abbbe7b81b.png)

So the conclusion is that you can define your own tags and so you can workaround. It is dirty, but it works

![image](https://user-images.githubusercontent.com/42182294/64261899-901fec80-cf2d-11e9-9706-c9802c347b55.png)

**Comment by g3blv** [comment]
Thx that work fine where I'm using. Doesn't seem to work in the live editor which doesn't matter for me.
