### ISSUE TITLE
Approved issues are being bot-locked

### ISSUE THREAD

**Issue by Logerfo** [knsv/mermaid#982]
Exampels: #487, #561.

**Comment by chris579** [comment]
Maybe this should be solved with github actions as I'm not aware that stale bot respects certain labels.

**Comment by knsv** [comment]
We need to look at the settings.

**Comment by Dunning-Kruger** [comment]
Hey, a couple of weeks ago we switched momentarily to a github action for marking stale issues/prs as stalebot was not working. We have since switched back to stalebot.

I believe that when the new activity occurred (after the inactive label was applied) stalebot was not running so it did not remove the label and, since no other activity occurred on the inactive issue, it was eventually closed.

Note that the bug is more aptly described as "issues with activity were not un-labeled as inactive".
There's no way for us to find all issues in this state besides checking one by one all "inactive". I reopened the ones you pointed out and will be happy to do so on any other anyone finds.

The tag `Status: Approved` does not prevent an issue from becoming inactive or being closed. Only the "Retained" tag does. The reasoning behind this is that if there's no interest from the community, the issues (even approved ones) should be left behind and make way for more recent/active ones.

The retained tag is applied only to bugs, missing stuff in documentation, or very specific issues, since they are perpetual.
